
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-18T15:39:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf4336cd08fb5106769e160f4e6eaf94e51e9a2d",
 "version": "0.9.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
