
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-05T10:58:09-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "1e5cf83f73e5dd74a5d15bd98260f431c26352fb",
 "version": "0.9.104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
