
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-12T14:58:48-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "ce2b312252515f5061c89e460427544bcb8fab53",
 "version": "0.9.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
